[package]
name = "clapstyle"
description = "Simple utility library to match your CLI's output to Clap's output."
repository = "https://github.com/Thijzert123/clapstyle"
readme = "README.md"
keywords = ["cli", "clap", "style", "color"]
categories = ["command-line-interface", "value-formatting"]
authors = ["Thijzert <184778919+Thijzert123@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.2"
rust-version = "1.88.0"
edition = "2024"

[package.metadata.docs.rs]
all-features = true

[features]
anyhow = ["dep:anyhow"]

[dependencies]
anstream = "1.0.0"
anstyle = "1.0.14"
anyhow = { version = "1.0.104", optional = true }
clap = "4.6.6"
duplicate = "2.0.1"
parking_lot = "0.12.5"
pastey = "0.2.3"

[[example]]
name = "anyhow"
required-features = ["anyhow"]
